import{S as p,a as f,i as c}from"./assets/vendor-B3Lscd_h.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const u=document.querySelector(".loader"),m=document.querySelector(".gallery");function g({webformatURL:o,largeImageURL:t,tags:i,likes:a,views:e,comments:r,downloads:n}){const h=i.split(",").slice(0,3).join(", ");return`<li>
          <a href="${t}"><img src="${o}" alt="${h}" width="360" height="152" />
          <div class="thumb">
          <h2>Likes<span class="item-text">${a}</span></h2>
          <h2>Views<span class="item-text">${e}</span></h2>
          <h2>Comments<span class="item-text">${r}</span></h2>
          <h2>Downloads<span class="item-text">${n}</span></h2>
          </div>
          </a>
        </li>`}function y(o){return o.map(g).join(`
`)}const L=new p(".gallery a",{captionDelay:250,captionsData:"alt",captions:!0});function b(){m.innerHTML=""}function S(o){const t=y(o);m.insertAdjacentHTML("afterbegin",t),L.refresh()}function w(){u.classList.remove("hidden")}function s(){u.classList.add("hidden")}const x="50463047-2395de4a1fa17e590ab2adb36",$="https://pixabay.com/api/";function v(o){const t=new URLSearchParams({key:x,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0});return f.get(`${$}?${t}`)}let l=null;const d=document.querySelector(".form");d.addEventListener("submit",q);s();function q(o){o.preventDefault(),l=o.target.elements["search-text"].value.trim(),b(),w(),v(l).then(t=>{if(t.data.hits.length===0){c.warning({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"}),s();return}S(t.data.hits),s(),d.reset()}).catch(t=>{s(),c.error({message:"Something went wrong!!!",position:"topRight"})})}
//# sourceMappingURL=index.js.map
